site_name: 'Прикладное программирование'
site_description: 'Методические материалы по курсу прикладного программирования'
theme:
  name: material

  palette:
    primary: 'indigo'
    accent: 'pink'

nav:
  - Главная: index.md
  - Основы Git:
      - Что такое Git: git/intro.md
      - Основные понятия Git: git/concepts.md
      - Глобальная установка Git: git/install.md
      - Жизненный цикл работы с Git: git/workflow.md
      - Слияние: git/merge.md
      - Откат версии: git/revert.md
      - Основные команды Git: git/commands.md
      - Что такое .gitignore: git/ignore.md
      - Инструменты: git/tools.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: >
  © 2025 Iana Malova. Курс прикладного программирования 2025 МГТУ "Станкин"

extra_css:
  - stylesheets/extra.css
